-- RetPlan database schema - PostgreSQL (12 or later)
--
-- This file and schema/sqlite.sql describe the same tables, columns, keys and
-- indexes; keep them in step. There are no migrations: on start-up RetPlan runs
-- this file when the database has no tables, and otherwise checks that every
-- table below exists. To change the schema, edit both files and rebuild (or
-- ALTER) the database yourself.
--
-- Conventions (chosen so the same SQL text runs unchanged on both engines):
--   * timestamps are ISO-8601 UTC text ("2026-09-29T14:03:11+00:00")
--   * dates are ISO-8601 text ("2026-09-29"), which sorts and compares correctly
--   * JSON documents are stored as text
--   * money and prices are DOUBLE PRECISION, matching SQLite's REAL

CREATE TABLE IF NOT EXISTS plans (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner       TEXT    NOT NULL,
    name        TEXT    NOT NULL,
    data        TEXT    NOT NULL,
    is_active   INTEGER NOT NULL DEFAULT 0 CHECK (is_active IN (0, 1)),
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_plans_owner ON plans (owner);

CREATE TABLE IF NOT EXISTS portfolios (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner       TEXT    NOT NULL,
    name        TEXT    NOT NULL,
    currency    TEXT    NOT NULL DEFAULT 'USD',
    description TEXT    NOT NULL DEFAULT '',
    settings    TEXT    NOT NULL DEFAULT '{}',
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_portfolios_owner ON portfolios (owner);

CREATE TABLE IF NOT EXISTS securities (
    symbol          TEXT PRIMARY KEY,
    name            TEXT NOT NULL DEFAULT '',
    quote_type      TEXT NOT NULL DEFAULT '',
    currency        TEXT NOT NULL DEFAULT '',
    exchange        TEXT NOT NULL DEFAULT '',
    asset_class     TEXT NOT NULL DEFAULT '',
    last_price      DOUBLE PRECISION,
    prev_close      DOUBLE PRECISION,
    last_price_date TEXT,
    fetched_at      TEXT,
    fetch_error     TEXT,
    lt_return       DOUBLE PRECISION,
    lt_vol          DOUBLE PRECISION,
    lt_years        DOUBLE PRECISION,
    lt_updated      TEXT,
    dividend_yield  DOUBLE PRECISION,
    source          TEXT NOT NULL DEFAULT 'yahoo',     -- yahoo | manual (prices typed in)
    collect         BIGINT  NOT NULL DEFAULT 0,
    keep_days       BIGINT,
    notes           TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS accounts (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner        TEXT    NOT NULL,
    name         TEXT    NOT NULL,
    type         TEXT    NOT NULL,
    owner_person BIGINT  NOT NULL DEFAULT 0,
    institution  TEXT    NOT NULL DEFAULT '',
    currency     TEXT    NOT NULL DEFAULT 'USD',
    value        DOUBLE PRECISION NOT NULL DEFAULT 0,
    as_of        TEXT,
    rate         DOUBLE PRECISION,
    payment      DOUBLE PRECISION,
    term_months  BIGINT,
    notes        TEXT    NOT NULL DEFAULT '',
    created_at   TEXT    NOT NULL,
    updated_at   TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_accounts_owner ON accounts (owner);

CREATE TABLE IF NOT EXISTS portfolio_accounts (
    portfolio_id BIGINT  NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    account_id   BIGINT  NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    position     BIGINT  NOT NULL DEFAULT 0,
    PRIMARY KEY (portfolio_id, account_id)
);
CREATE INDEX IF NOT EXISTS ix_portfolio_accounts_account ON portfolio_accounts (account_id);

CREATE TABLE IF NOT EXISTS portfolio_children (
    parent_id    BIGINT  NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    child_id     BIGINT  NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    position     BIGINT  NOT NULL DEFAULT 0,
    PRIMARY KEY (parent_id, child_id)
);
CREATE INDEX IF NOT EXISTS ix_portfolio_children_child ON portfolio_children (child_id);

CREATE TABLE IF NOT EXISTS holdings (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT  NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    symbol       TEXT    NOT NULL REFERENCES securities (symbol),
    quantity     DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_basis   DOUBLE PRECISION,
    asset_class  TEXT    NOT NULL DEFAULT '',
    notes        TEXT    NOT NULL DEFAULT '',
    added_at     TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_holdings_account ON holdings (account_id);
CREATE INDEX IF NOT EXISTS ix_holdings_symbol ON holdings (symbol);

CREATE TABLE IF NOT EXISTS prices (
    symbol    TEXT NOT NULL REFERENCES securities (symbol) ON DELETE CASCADE,
    date      TEXT NOT NULL,
    close     DOUBLE PRECISION NOT NULL,
    adj_close DOUBLE PRECISION NOT NULL,
    volume    DOUBLE PRECISION,
    open      DOUBLE PRECISION,
    high      DOUBLE PRECISION,
    low       DOUBLE PRECISION,
    PRIMARY KEY (symbol, date)
);
CREATE INDEX IF NOT EXISTS ix_prices_date ON prices (date);

CREATE TABLE IF NOT EXISTS price_gaps (
    symbol     TEXT    NOT NULL REFERENCES securities (symbol) ON DELETE CASCADE,
    date       TEXT    NOT NULL,
    attempts   BIGINT  NOT NULL DEFAULT 0,
    last_tried TEXT    NOT NULL,
    PRIMARY KEY (symbol, date)
);

CREATE TABLE IF NOT EXISTS fetch_runs (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason      TEXT    NOT NULL,
    started_at  TEXT    NOT NULL,
    finished_at TEXT,
    symbols     INTEGER NOT NULL DEFAULT 0,
    ok          INTEGER NOT NULL DEFAULT 0,
    failed      INTEGER NOT NULL DEFAULT 0,
    rows_added  INTEGER NOT NULL DEFAULT 0,
    rows_pruned INTEGER NOT NULL DEFAULT 0,
    message     TEXT    NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS projections (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT  NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE,
    created_at   TEXT    NOT NULL,
    settings     TEXT    NOT NULL,
    summary      TEXT    NOT NULL,
    result       TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_projections_portfolio ON projections (portfolio_id);

CREATE TABLE IF NOT EXISTS import_drafts (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner       TEXT    NOT NULL,
    filename    TEXT    NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL,
    data        TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_import_drafts_owner ON import_drafts (owner);

CREATE TABLE IF NOT EXISTS snapshots (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner       TEXT    NOT NULL,
    taken_on    TEXT    NOT NULL,
    kind        TEXT    NOT NULL DEFAULT 'all',
    ref         TEXT    NOT NULL DEFAULT '',
    assets      DOUBLE PRECISION NOT NULL DEFAULT 0,
    liabilities DOUBLE PRECISION NOT NULL DEFAULT 0,
    data        TEXT    NOT NULL DEFAULT '{}',
    note        TEXT    NOT NULL DEFAULT '',
    created_at  TEXT    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_snapshots_day ON snapshots (owner, taken_on, kind, ref);

CREATE TABLE IF NOT EXISTS app_settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
